#!/usr/bin/env bash
# Regenerate dock.jsonc and dock-pinned.css from dock-apps.json,
# then restart the waybar dock.
#
# Generated layout:
#   modules-center = [ <pre-taskbar...>, wlr/taskbar, <post-taskbar...> ]
# Entries with "post_taskbar": true go after the taskbar (e.g. settings, trash),
# all others before. Backward-compat fallback: if none has post_taskbar,
# the last entry is treated as post.
set -euo pipefail

cfg="$HOME/.config/waybar"
apps="$cfg/dock-apps.json"
out_json="$cfg/dock.jsonc"
out_css="$cfg/dock-pinned.css"

[[ -f "$apps" ]] || { echo "missing $apps" >&2; exit 1; }

count=$(jq 'length' "$apps")
(( count > 0 )) || { echo "dock-apps.json empty" >&2; exit 1; }

ids=()
post_ids=()
pinned_ids=()
while IFS= read -r entry; do
  id=$(jq -r .id <<<"$entry")
  post=$(jq -r '.post_taskbar // false' <<<"$entry")
  ids+=("$id")
  if [[ "$post" == "true" ]]; then
    post_ids+=("$id")
  else
    pinned_ids+=("$id")
  fi
done < <(jq -c '.[]' "$apps")

# Backward-compat: if no post_taskbar, move the last one into post
if (( ${#post_ids[@]} == 0 )); then
  post_ids=("${pinned_ids[-1]}")
  unset 'pinned_ids[-1]'
fi

# ── modules-center array ─────────────────────────────────────────────
center='['
first=1
for id in "${pinned_ids[@]}"; do
  (( first )) || center+=","
  center+="\"custom/$id\""
  first=0
done
(( first )) || center+=","
center+='"wlr/taskbar"'
for id in "${post_ids[@]}"; do
  center+=",\"custom/$id\""
done
center+=']'

# ── per-app module blocks (custom/<id>) ──────────────────────────────
modules=""
for id in "${ids[@]}"; do
  modules+="$(jq -nc --arg id "$id" \
    '{
      ("custom/"+$id): {
        "exec": ("__HOME__/.config/waybar/dock-status.sh " + $id),
        "interval": 1,
        "return-type": "json",
        "tooltip": true,
        "on-click": ("__HOME__/.config/waybar/dock-click.sh " + $id)
      }
    }')"
  modules+=$'\n'
done

# ── wlr/taskbar ignore-list: all app_ids declared in the pinned entries ──
ignore_json=$(jq -c '[.[].app_ids // [] | .[]] | unique' "$apps")

# ── compose final dock.jsonc ─────────────────────────────────────────
{
  echo '// Waybar dock for niri (generated by dock-gen.sh — do not edit by hand).'
  echo '// Source: dock-apps.json'
  jq -n \
    --argjson center "$center" \
    --argjson ignore "$ignore_json" \
    --slurpfile mods <(printf '%s' "$modules" | jq -s 'add') \
    '{
      "layer": "top",
      "position": "bottom",
      "height": 52,
      "spacing": 6,
      "margin-bottom": 10,
      "margin-left": 6,
      "margin-right": 6,
      "modules-left": [],
      "modules-center": $center,
      "modules-right": [],
      "wlr/taskbar": {
        "format": "{icon}",
        "icon-size": 32,
        "tooltip-format": "{title}",
        "on-click": "activate",
        "on-click-middle": "close",
        "ignore-list": $ignore
      }
    } * $mods[0]'
} > "$out_json"

# ── dock-pinned.css: common rules + icon from GTK theme + color ──────
{
  echo "/* Generated by dock-gen.sh — do not edit by hand. */"

  # Common rules applied to ALL modules (pinned + post-taskbar).
  # Single selector = CSV list of IDs, in array order.
  joined=""
  for id in "${ids[@]}"; do
    [[ -n "$joined" ]] && joined+=","
    joined+="#custom-${id}"
  done

  echo "${joined} {"
  echo "  padding: 0;"
  echo "  margin: 6px 3px;"
  echo "  min-width: 36px;"
  echo "  min-height: 40px;"
  echo "  border-radius: 12px;"
  echo "  background-color: transparent;"
  echo "  background-repeat: no-repeat;"
  echo "  background-position: center 30%;"
  echo "  background-size: 28px 28px;"
  echo "  transition: background-color 120ms ease;"
  echo "}"

  hover=""
  running=""
  for id in "${ids[@]}"; do
    [[ -n "$hover" ]] && hover+=","
    hover+="#custom-${id}:hover"
    [[ -n "$running" ]] && running+=","
    running+="#custom-${id}.running"
  done

  echo "${hover} {"
  echo "  background-color: rgba(138, 173, 244, 0.28);"
  echo "  color: #ffffff;"
  echo "}"

  # "running" indicator: short centered bar at the bottom (NOT full-width).
  # Emitted per-icon in the loop below as a background layer, so it stays
  # centered and does not cover the icon. Bar width = 50%, thickness 3px.

  while IFS= read -r entry; do
    id=$(jq -r .id        <<<"$entry")
    color=$(jq -r .color  <<<"$entry")
    icon_name=$(jq -r '.icon_name // ""' <<<"$entry")
    icon_path=""
    if [[ -n "$icon_name" ]]; then
      icon_path=$(python3 - "$icon_name" <<'PY'
import sys, gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk
name = sys.argv[1]
info = Gtk.IconTheme.get_default().lookup_icon(name, 48, 0)
print(info.get_filename() if info else "")
PY
)
    fi
    bar="linear-gradient(#d6edff, #d6edff)"   # solid bar (light blue toward white)
    if [[ -n "$icon_path" ]]; then
      echo "#custom-${id} { background-image: url(\"${icon_path}\"); color: ${color}; }"
      echo "#custom-${id}.running { background-image: url(\"${icon_path}\"), ${bar}; background-size: 28px 28px, 50% 3px; background-position: center 30%, center bottom; background-repeat: no-repeat, no-repeat; }"
    else
      echo "#custom-${id} { color: ${color}; }"
      echo "#custom-${id}.running { background-image: ${bar}; background-size: 50% 3px; background-position: center bottom; background-repeat: no-repeat; }"
    fi
  done < <(jq -c '.[]' "$apps")
} > "$out_css"

# ── restart dock waybar ──────────────────────────────────────────────
if [[ "${1:-}" != "--no-reload" ]]; then
  pkill -f "waybar -c .*dock.jsonc" 2>/dev/null || true
  sleep 0.4
  setsid sh -c "waybar -c $out_json -s $cfg/dock.css" >/tmp/waybar-dock.log 2>&1 < /dev/null &
  disown 2>/dev/null || true
fi

echo "Dock regenerated: $count apps (${#pinned_ids[@]} pre-taskbar, ${#post_ids[@]} post-taskbar: ${post_ids[*]})."
